apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::996669628469:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-UoBjcv8VcXTP
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::996669628469:user/suresh
      username: suresh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::996669628469:user/john
      username: john
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::996669628469:user/rahim
      username: rahim
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::996669628469:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-16T08:13:36Z"
  name: aws-auth
  namespace: kube-system
  uid: e32c1bee-5aeb-4984-bb38-e6a9251737b4