apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::996669628469:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-7PJ4EU8bFJaf
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop